// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtyyrpzxvfxnxwnppndx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eXlycHp4dmZ4bnh3bnBwbmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njk5NTAsImV4cCI6MjA2NTU0NTk1MH0.6prtqZlDFyA4GodAaLQGcVOBRKEZHQv1TTi-kccnSXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);